post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [
    path('', views.PostListView.as_view(), name="list"),
]

taiwanpanda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path("user/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
#from django.conf.urls import url
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path("", views.TopView.as_view(), name="top"),
    path("home/", views.HomeView.as_view(), name="home"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path('register/', views.AccountRegistration.as_view(), name='register'),
]

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    description = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    likes_count = models.IntegerField(default=0)

users/models.py
from django.db import models
# ユーザー認証
from django.contrib.auth.models import User

#左がDBに登録、右が表示される値
GRADUATE_CHOICES = [(24,24), (25,25), (26,26), (27,27), (28,28)]

# Create your models here.
class Account(models.Model):
    # ユーザー(ユーザー名、パスワード、メールアドレス）
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    last_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    icon_image = models.ImageField(upload_to='icons/')  # Specify the directory where images will be stored
    graduate_at = models.IntegerField(choices=GRADUATE_CHOICES, verbose_name='卒業年')
    graduate_at_summer = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username

users/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from .models import Account

class UserLoginForm(forms.Form):
    username = forms.CharField(label='ユーザーネーム')
    password = forms.CharField(label='パスワード')

# フォームクラス作成
class AccountForm(forms.ModelForm):
    # パスワード入力：非表示対応
    password = forms.CharField(widget=forms.PasswordInput(),label="パスワード")
    password_confirmation = forms.CharField(widget=forms.PasswordInput(), label="パスワード確認")

    class Meta():
        # ユーザー認証
        model = User
        # フィールド指定
        fields = ('username','email','password','password_confirmation')
        # フィールド名指定
        labels = {'username':"ユーザーID",'email':"メール"}
    
    prefix = 'account'

class AddAccountForm(forms.ModelForm):
    class Meta():
        # モデルクラスを指定
        model = Account
        fields = ('last_name','first_name','icon_image','graduate_at','graduate_at_summer')
        labels = {'last_name':"苗字",'first_name':"名前",'icon_image':"写真アップロード",'graduate_at':'卒業年','graduate_at_summer':'夏卒or冬卒'}

    prefix = 'add'

post/views.py
from django.shortcuts import render
from django.views import generic
from post.models import Post

# Create your views here.
class PostListView(generic.ListView):
    template_name = "post/list.html"
    model = Post

users/views.py
from typing import Any
from django.shortcuts import render
from django.views import generic
from users.models import Account
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, FormView
from .forms import AccountForm, AddAccountForm # ユーザーアカウントフォーム
from django.contrib.auth import authenticate
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from .forms import UserLoginForm
from . import forms

# Create your views here.
class TopView(TemplateView):
    template_name = "users/top.html"

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "users/home.html"

class LoginView(FormView):
    """ログインページ"""
    form_class = UserLoginForm
    template_name = "users/login.html"

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        print(request.POST)
        if user:
            account = Account.objects.get(user=user)
            context = {
                'user_name' : user.username,
                'user_email' : user.email,
                'user_icon_image' : account.icon_image,
                'user_graduate_at' : account.graduate_at,
                'user_graduate_at_summer' : account.graduate_at_summer,
            }
            return render(request, 'users/home.html', context)
        else:
            return render(request, 'users/login.html')
        

class LogoutView(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = "users/login.html"

class AccountRegistration(TemplateView):

    def get(self, request, *args, **kwargs):
        context = {
            'account_form': AccountForm(),
            'add_form': AddAccountForm(),
        }
        return render(request, 'users/register.html', context)
    
    def post(self, request):
        add_form = AddAccountForm(request.POST, request.FILES, prefix='add')
        account_form = AccountForm(request.POST, prefix='account')

        if account_form.is_valid() and add_form.is_valid():
            new_account = account_form.save()
            new_add = add_form.save(commit=False)
            new_add.user = new_account
            new_add.save()
            context = {
                'user_name' : new_add.user.username,
                'user_email' : new_add.user.email,
                'user_icon_image' : new_add.icon_image,
                'user_graduate_at' : new_add.graduate_at,
                'user_graduate_at_summer' : new_add.graduate_at_summer,
            }
            return render(request, 'users/home.html', context)
        else:
            context = {
                'account_form': account_form,
                'add_form': add_form,
            }
            return render(request, 'users/register.html', context)
        

templates/post/list.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Fenxiangs</title>
        <link rel="stylesheet" href='{% static "post/list.css" %}' />
    </head>

    <header>  
    <!-- メニューバー -->
            <div class="header_wrapper">
                <h1>
                    <a href="#">Fenxiangs</a>
                </h1>
            </div>

        <nav class="gnav">
            <ul class="gnav_wrapper">
                <li><a href="#">ホーム</a></li>
                <li><a href="#">#times</a></li>
            </ul>
        </nav>
        
    <!-- ログイン＆ログアウト -->




    <!-- fixed title -->
        <img src="{% static 'assets/パンダ.png' %}" alt="webicon">







    </header>

  


    <body>
     
    <!-- 投稿フィード -->
    {% for post in object_list %}
    <p>{{ post.description }}</p>
    <p>{{ post.created_at }}</p>
    <p>{{ post.likes_count }}</p>
    {% endfor %}





    </body>


    <footer>


    </footer>

</html>

templates/users/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    {% block content %}{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/users/home.html
{% extends "users/base.html" %}
{% block title %}ホーム{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5"></h1>
    <p>{{ user_name }}さん、こんにちは。</p>
    <p>{{ user_email }}</p>
    <img src="{{ user_icon_image.url }}" />  <!-- Ensure the image URL is correct -->
    <p>{{ user_graduate_at }}</p>
    <p>Summer Graduate: {{ user_graduate_at_summer }}</p> <!-- For more user-friendly display of Boolean -->
    <a href="{% url 'users:logout' %}">ログアウト</a>
</div>
{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}
{% block title %}ログイン{% endblock %}

{% block content %}
<div class="container">
    <h1>ログイン</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <button type="submit">ログイン</button>
    </form>
</div>
{% endblock %}

templates/users/register.html
<!DOCTYPE html>
{% load static %}
<html lang="ja" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href='{% static "users/style.css" %}' />
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@300&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Agbalumo&family=Zen+Maru+Gothic:wght@300&display=swap" rel="stylesheet">
</head>

<body>
  <header>
    <p class="icon">fenxiangs</p>
  </header>
  <h1>新規登録</h1>
  <div class="reg">
    <table class="reg_form">

      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ account_form.as_p }}
        {{ add_form.as_p }}
        <tr>
          <td></td>
          <td>
            <input class="btn" type="submit" name="" value="登録">
          </td>
        </tr>
      </form>
    </table>
  </div>
</body>

</html>

templates/users/top.html
{% extends "users/base.html" %}

{% block title %}トップ{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5">Top画面</h1>
    <a href="{% url 'users:login' %}" class="btn btn-outline-primary">ログイン</a>
</div>
{% endblock %}

templates/users/users.html
<h1>ユーザー一覧</h1>
{% for user in object_list %}
    <p>{{ user.name }}</p>
    <p>{{ user.email }}</p>
    <img src="{{ user.icon_image.url }}" alt="{{ user.name }}'s icon" />  <!-- Ensure the image URL is correct -->
    <p>{{ user.graduate_at }}</p>
    <p>Summer Graduate: {{ user.graduate_at_summer|yesno:"Yes,No" }}</p> <!-- For more user-friendly display of Boolean -->
{% endfor %}